--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
  - !ruby/struct:SM::Flow::P 
    body: "Alias for #config"
full_name: Compass::Installers::TemplateContext#configuration
is_singleton: false
name: configuration
params: ()
visibility: public
