--- !ruby/object:RI::MethodDescription 
aliases: 
  - !ruby/object:RI::AliasName 
    name: configuration
block_params: 
comment: 
full_name: Compass::Installers::TemplateContext#config
is_singleton: false
name: config
params: ()
visibility: public
