--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
constants: []

full_name: Rails::Railtie::Configuration
includes: []

instance_methods: 
  - !ruby/object:RI::MethodSummary 
    name: compass
name: Configuration
superclass: Object
