--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
  - !ruby/struct:SM::Flow::P 
    body: Registers a new configuration property. Extensions can use this to add new configuration options to compass.
  - !ruby/struct:SM::Flow::P 
    body: "@param [Symbol] name The name of the property. @param [String] comment A comment for the property. @param [Proc] default A method to calculate the default value for the property."
  - !ruby/struct:SM::Flow::VERB 
    body: "                      The proc is executed in the context of the project's configuration data.\n"
full_name: Compass::Configuration::add_configuration_property
is_singleton: true
name: add_configuration_property
params: (name, comment = nil, &default)
visibility: public
