--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: 
  - !ruby/object:RI::MethodSummary 
    name: add_configuration_property
  - !ruby/object:RI::MethodSummary 
    name: attributes_for_directory
  - !ruby/object:RI::MethodSummary 
    name: remove_configuration_property
comment: 
constants: 
  - !ruby/object:RI::Constant 
    comment: 
    name: ATTRIBUTES
    value: "[       # What kind of project?       :project_type,       # Where is the project?       :project_path,       :http_path,       # Where are the various bits of the project       attributes_for_directory(:css, :stylesheets),       attributes_for_directory(:sass, nil),       attributes_for_directory(:images),       attributes_for_directory(:javascripts),       attributes_for_directory(:fonts),       attributes_for_directory(:extensions, nil),       # Compilation options       :output_style,       :environment,       :relative_assets,       :additional_import_paths,       :sass_options,       attributes_for_directory(:cache, nil),       :cache,       # Helper configuration       :asset_host,       :asset_cache_buster,       :line_comments,       :color_output,       :preferred_syntax,       :disable_warnings,       :sprite_engine,       :chunky_png_options"
full_name: Compass::Configuration
includes: []

instance_methods: []

name: Configuration
superclass: 
