--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
  - !ruby/struct:SM::Flow::P 
    body: For testing purposes
full_name: Compass::Configuration::remove_configuration_property
is_singleton: true
name: remove_configuration_property
params: (name)
visibility: public
