--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
constants: []

full_name: Compass::Commands::ConfigurationOptionsParser
includes: []

instance_methods: 
  - !ruby/object:RI::MethodSummary 
    name: set_options
name: ConfigurationOptionsParser
superclass: 
