--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Compass::AppIntegration::Rails::ConfigurationDefaults#default_environment
is_singleton: false
name: default_environment
params: ()
visibility: public
