--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
  - !ruby/struct:SM::Flow::P 
    body: "Composes a pixel on the canvas by alpha blending a color with its background color, without bounds checking. @param (see #compose_pixel) @return [Integer] The composed color."
full_name: ChunkyPNG::Canvas::Drawing#compose_pixel_unsafe
is_singleton: false
name: compose_pixel_unsafe
params: (x, y, color)
visibility: public
