--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
  - !ruby/struct:SM::Flow::P 
    body: Determines if the configuration file is newer than any css file
full_name: Compass::Compiler#new_config?
is_singleton: false
name: new_config?
params: ()
visibility: public
