--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
  - !ruby/struct:SM::Flow::P 
    body: Determines the most suitable colormode for this palette. @return [Integer] The colormode which would create the smallest possible
  - !ruby/struct:SM::Flow::VERB 
    body: "   file for images that use this exact palette.\n"
full_name: ChunkyPNG::Palette#best_color_settings
is_singleton: false
name: best_color_settings
params: ()
visibility: public
