--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Compass::Commands::ProjectBase#add_project_configuration
is_singleton: false
name: add_project_configuration
params: ()
visibility: protected
