--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Compass::AppIntegration::Rails::Installer#gem_config_instructions
is_singleton: false
name: gem_config_instructions
params: ()
visibility: public
