--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Compass::AppIntegration::StandAlone::Installer#completed_configuration
is_singleton: false
name: completed_configuration
params: ()
visibility: public
