--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Compass::Configuration::Helpers#add_configuration
is_singleton: false
name: add_configuration
params: (config, filename = nil)
visibility: public
