--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Compass::Configuration::Helpers#default_configuration
is_singleton: false
name: default_configuration
params: ()
visibility: public
