--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
  - !ruby/struct:SM::Flow::P 
    body: Finds the configuration file, if it exists in a known location.
full_name: Compass::Configuration::Helpers#detect_configuration_file
is_singleton: false
name: detect_configuration_file
params: (project_path = nil)
visibility: public
