--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Compass::AppIntegration::Rails#configuration
is_singleton: false
name: configuration
params: ()
visibility: public
