--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Compass::Installers::Manifest#generate_config?
is_singleton: false
name: generate_config?
params: ()
visibility: public
