--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Compass::Installers::Manifest#no_configuration_file!
is_singleton: false
name: no_configuration_file!
params: ()
visibility: protected
