--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: 
  - !ruby/object:RI::MethodSummary 
    name: description
  - !ruby/object:RI::MethodSummary 
    name: new
  - !ruby/object:RI::MethodSummary 
    name: option_parser
  - !ruby/object:RI::MethodSummary 
    name: parse!
  - !ruby/object:RI::MethodSummary 
    name: parse_arguments!
  - !ruby/object:RI::MethodSummary 
    name: usage
comment: 
constants: []

full_name: Compass::Commands::WriteConfiguration
includes: 
  - !ruby/object:RI::IncludedModule 
    name: InstallerCommand
instance_methods: 
  - !ruby/object:RI::MethodSummary 
    name: add_project_configuration
  - !ruby/object:RI::MethodSummary 
    name: explicit_config_file_must_be_readable?
  - !ruby/object:RI::MethodSummary 
    name: installer_args
  - !ruby/object:RI::MethodSummary 
    name: perform
name: WriteConfiguration
superclass: ProjectBase
