--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
  - !ruby/struct:SM::Flow::P 
    body: Decomposes the alpha channels for the r, g and b color channel. @param [Integer] color The color that was the result of compositing. @param [Integer] mask The opaque variant of the color that was being composed @param [Integer] bg The background color on which the color was composed. @return [Array&lt;Integer&gt;] The decomposed alpha values for the r, g and b channels.
full_name: ChunkyPNG::Color#decompose_alpha_components
is_singleton: false
name: decompose_alpha_components
params: (color, mask, bg)
visibility: public
